<?php

namespace GravityPdf\Upload;

use Closure;
use Yoast\PHPUnitPolyfills\TestCases\TestCase;

/**
 * The shipped `.pot` is generated by `composer i18n:pot`, and the `i18n` workflow regenerates
 * it and fails on a diff, which is what keeps it in step with the source. These are the
 * assertions that check cannot make: that the strings an extractor cannot see are in there
 * anyway, and that the ones policy says are not translated have stayed out.
 */
class CatalogueTest extends TestCase
{
    /**
     * @var string[]
     */
    protected $msgids = [];

    /* phpcs:ignore */
    public function set_up()
    {
        parent::set_up();

        $catalogue = (string) file_get_contents(dirname(__DIR__, 2) . '/i18n/upload.pot');

        /* Enough of a `.po` reader for a file this library generates itself: single-line
           msgids, and the continuation lines `xgettext` wraps a long one across */
        preg_match_all('/^msgid "(.*)"$((?:\n^".*"$)*)/m', $catalogue, $matches, PREG_SET_ORDER);

        foreach ($matches as $match) {
            $msgid = $match[1] . str_replace(["\n\"", "\"\n", '"'], '', $match[2]);

            if ($msgid !== '') {
                $this->msgids[] = str_replace('\"', '"', $msgid);
            }
        }
    }

    /**
     * The seven `UPLOAD_ERR_*` strings are array values, not call arguments, so no extraction
     * keyword reaches them. The marker around each is the only reason they are in the
     * catalogue; drop it and they leave silently.
     *
     * Read through a bound closure because `ReflectionMethod::setAccessible()` is deprecated
     * as of PHP 8.5.
     */
    public function testEveryUploadErrorMessageIsInTheCatalogue(): void
    {
        $reader = Closure::bind(static function (): array {
            return File::getUploadErrorMessages();
        }, null, File::class);

        $messages = $reader();

        $this->assertCount(7, $messages);

        foreach ($messages as $message) {
            $this->assertContains($message, $this->msgids);
        }

        /* The fallback for a code with no message of its own, which is a separate literal */
        $this->assertContains('Unknown error', $this->msgids);
    }

    /**
     * @dataProvider provideMessagesTheCollectionRecords
     */
    public function testEveryRecordedMessageIsInTheCatalogue(string $message): void
    {
        $this->assertContains($message, $this->msgids);
    }

    /** @return array<string,array<int,string>> */
    public function provideMessagesTheCollectionRecords(): array
    {
        return [
            'malformed entry' => ['An uploaded file was sent in a format that cannot be read'],
            'not an upload' => ['This file was not received as an upload'],
            'absorbed throwable' => ['Validation could not be completed'],
            'size unknown' => ['File size could not be determined'],
            'size too small' => ['File size is too small. Must be at least %1$s bytes'],
            'size too large' => ['File size is too large. Must be no more than %1$s bytes'],
            'extension' => ['Invalid file extension. Must be one of: %1$s'],
            'mimetype' => ['Invalid mimetype. Must be one of: %1$s'],
            'contents' => ['File contents do not match the "%1$s" extension. Must be one of: %2$s'],
        ];
    }

    /**
     * Storage messages are not translated, so they must not be offered to a translator: they
     * name the destination, they are written for a log rather than for whoever submitted the
     * file, and `File` never looks one up. Neither are the two `Exception`s the collection
     * throws — the detail a caller shows is in `getErrors()`, and these are what they log.
     *
     * @dataProvider provideMessagesThatAreNeverTranslated
     */
    public function testMessagesThatAreNeverLookedUpAreNotInTheCatalogue(string $message): void
    {
        $this->assertNotContains($message, $this->msgids);
    }

    /** @return array<string,array<int,string>> */
    public function provideMessagesThatAreNeverTranslated(): array
    {
        return [
            'symlink' => ['Destination is a symbolic link'],
            'move failed' => ['File could not be moved to final destination.'],
            'collision' => ['A file named "%1$s" already exists'],
            'blocked extension' => ['Files with the extension "%1$s" cannot be stored'],
            'invalid name' => ['Invalid destination file name'],
            'validation failed' => ['File validation failed'],
            'nothing to upload' => ['There are no files to upload'],
        ];
    }
}
