<?php

/**
 * Regenerate `i18n/upload.pot`, the catalogue of every string this library shows an end user
 *
 * Run with `composer i18n:pot`. The `i18n` workflow runs the same thing and fails on a diff,
 * so a reworded message cannot silently orphan the translations a consumer already has for it.
 *
 * ## What is in the catalogue, and what is deliberately not
 *
 * Whatever is marked with `GravityPdf\Upload\__()`, which is exactly what `File` looks up.
 * That is narrower than "every string in `src/`", and the narrowing is the marker's doing
 * rather than this script's:
 *
 * - `Storage\FileSystem`'s messages are unmarked and never translated. A storage message names
 *   the destination and is written for a log (see `reserveDestination()` on why showing one is
 *   an existence oracle).
 * - `File`'s own `Exception` messages — `File validation failed`, `There are no files to
 *   upload` — are unmarked for the same reason. The detail a caller shows is in `getErrors()`.
 *
 * ## Why GNU gettext rather than a PHP extractor
 *
 * One flag against a marker that does nothing but return its argument, so a PHP-based scanner
 * would do no better here and `tools/i18n/` needs no manifest of its own. A consumer
 * generating their own catalogue from `vendor/` runs the same flag. It matches the fully
 * qualified `\GravityPdf\Upload\__()` as well as the imported short form.
 *
 * `-k__:1` reads the first argument and ignores the marker's `$domain`. Do not "complete" it
 * to `-k__:1,2`: gettext reads a second argument number as the plural form, no call in `src`
 * has that shape, and the run extracts nothing while still exiting 0.
 *
 * @package Upload
 */

declare(strict_types=1);

$root = dirname(__DIR__, 2);

exec('command -v xgettext', $found, $status);

if ($status !== 0) {
    fwrite(STDERR, "xgettext is not installed. `brew install gettext` or `apt-get install gettext`.\n");
    exit(1);
}

$sources = [];

/** @var SplFileInfo $file */
foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root . '/src')) as $file) {
    if ($file->isFile() && $file->getExtension() === 'php') {
        $sources[] = $file->getPathname();
    }
}

sort($sources);

if ($sources === []) {
    fwrite(STDERR, "No source files found.\n");
    exit(1);
}

$destination = tempnam(sys_get_temp_dir(), 'upload-pot');

if ($destination === false) {
    fwrite(STDERR, "Could not create a temporary file.\n");
    exit(1);
}

/* `--no-location` and `--no-wrap`: a catalogue carrying `#: src/Upload/File.php:412` changes
   whenever anything above line 412 does, and one wrapped at the installed gettext's preferred
   column changes with the runner's version. Either would fail the check that fails on a diff
   for a change nobody made. The translator comments carry the context the line numbers would.
   `--sort-output` for a stable order; it is deprecated on xgettext, so msgcat does it. */
$arguments = array_merge([
    '--language=PHP',
    '--from-code=UTF-8',
    '--add-comments=translators:',
    '--no-location',
    '--no-wrap',
    '--omit-header',
    '-k',
    '-k__:1',
    '-o',
    $destination,
], $sources);

/* Staged through a file rather than piped into msgcat, so the two exit statuses stay apart: a
   pipeline reports only its last command, and an xgettext that never ran would surface as an
   empty catalogue rather than a failure. */
exec('xgettext ' . implode(' ', array_map('escapeshellarg', $arguments)), $output, $status);

if ($status !== 0) {
    fwrite(STDERR, "xgettext failed:\n" . implode("\n", $output) . "\n");
    exit(1);
}

exec('msgcat --sort-output --no-wrap ' . escapeshellarg($destination), $sorted, $status);

unlink($destination);

if ($status !== 0) {
    fwrite(STDERR, "msgcat failed:\n" . implode("\n", $sorted) . "\n");
    exit(1);
}

/* A header written here rather than by xgettext, whose `POT-Creation-Date` changes on every
   run and would make the check that fails on a diff fail every time */
$header = <<<'POT'
# Translation catalogue for gravitypdf/upload.
#
# This is a template. No translations ship with this library, and none are needed: with no
# translator installed every message is the English source string below, which is also its
# msgid. Install one with `GravityPdf\Upload\Translation::setTranslator()`.
#
# Generated by `composer i18n:pot` — do not edit by hand.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: gravitypdf/upload\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

POT;

if (!is_dir($root . '/i18n') && !mkdir($root . '/i18n', 0755, true)) {
    fwrite(STDERR, "Could not create i18n/.\n");
    exit(1);
}

/* No header to strip: `--omit-header` means xgettext writes none and msgcat invents none, so
   msgcat's output starts at the first real msgid. */
file_put_contents($root . '/i18n/upload.pot', $header . "\n" . trim(implode("\n", $sorted)) . "\n");

echo "Wrote i18n/upload.pot\n";
